.import '../benchmark/csv_data/AccountPermission.csv' account_permission
.import '../benchmark/csv_data/Customer.csv' customer
.import '../benchmark/csv_data/CustomerAccount.csv' customer_account
.import '../benchmark/csv_data/CustomerTaxrate.csv' customer_taxrate
.import '../benchmark/csv_data/Holding.csv' holding
.import '../benchmark/csv_data/HoldingHistory.csv' holding_history
.import '../benchmark/csv_data/HoldingSummary.csv' holding_summary
.import '../benchmark/csv_data/WatchItem.csv' watch_item
.import '../benchmark/csv_data/WatchList.csv' watch_list
.import '../benchmark/csv_data/Broker.csv' broker
.import '../benchmark/csv_data/CashTransaction.csv' cash_transaction
.import '../benchmark/csv_data/Charge.csv' charge
.import '../benchmark/csv_data/CommissionRate.csv' commission_rate
.import '../benchmark/csv_data/Settlement.csv' settlement
.import '../benchmark/csv_data/Trade.csv' trade
.import '../benchmark/csv_data/TradeHistory.csv' trade_history
.import '../benchmark/csv_data/TradeType.csv' trade_type
.import '../benchmark/csv_data/Company.csv' company
.import '../benchmark/csv_data/CompanyCompetitor.csv' company_competitor
.import '../benchmark/csv_data/DailyMarket.csv' daily_market
.import '../benchmark/csv_data/Exchange.csv' exchange
.import '../benchmark/csv_data/Financial.csv' financial
.import '../benchmark/csv_data/Industry.csv' industry
.import '../benchmark/csv_data/LastTrade.csv' last_trade
.import '../benchmark/csv_data/NewsItem.csv' news_item
.import '../benchmark/csv_data/NewsXRef.csv' news_xref
.import '../benchmark/csv_data/Sector.csv' sector
.import '../benchmark/csv_data/Security.csv' security
.import '../benchmark/csv_data/Address.csv' address
.import '../benchmark/csv_data/StatusType.csv' status_type
.import '../benchmark/csv_data/TaxRate.csv' taxrate
.import '../benchmark/csv_data/ZipCode.csv' zip_code
